### ISSUE TITLE
Error message when creating mysql database for the first time

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba-gradle-plugin#119]
### Environment
- Platform version: 7.1.1
- Gradle version: 4.10.3

### Description of the bug or enhancement
See Studio ticket: https://youtrack.cuba-platform.com/issue/STUDIO-7049

Steps:
- create new project, take mysql as database
- drop the database if it already exists with this name
- run "gradlew createDb"

You see error in the task output:
```
budarov@budarov-B250M-DS3H:~/projects/testdrop$ gw createDb

> Task :app-core:createDb
[CubaDbCreation] Failed to execute SQL: drop database testdrop;
Error: Can't drop database 'testdrop'; database doesn't exist
Using database URL: jdbc:mysql://localhost/testdrop?useSSL=false&allowMultiQueries=true&serverTimezone=UTC, user: cuba
Executing SQL script: /home/budarov/projects/testdrop/modules/core/build/db/10-cuba/init/mysql/create-db.sql

BUILD SUCCESSFUL in 2s
2 actionable tasks: 1 executed, 1 up-to-date
```

Although task finishes successfully, IDEA reacts on the error message as something bad has happened.

**Comment by alexbudarov** [comment]
screenshot:
![image](https://user-images.githubusercontent.com/6158807/67204465-922b0580-f41e-11e9-9724-8a1fa194e08e.png)

**Comment by IskandarovRost** [comment]
And the same will be for MSSQL

**Comment by dtsaryov** [comment]
Related to https://github.com/cuba-platform/cuba-gradle-plugin/issues/115
