### ISSUE TITLE
CubaDbScriptsAssembling: DB scripts numbering stops on 100

### ISSUE THREAD

**Issue by IskandarovRost** [cuba-platform/cuba-gradle-plugin#139]
### Environment

- Platform version: 7.2.3
### Description of the bug or enhancement

See https://www.cuba-platform.com/discuss/t/incorrect-number-prefix-on-components/12042

- Minimal reproducible example
1) Create several projects which turn to a chain of dependencies
2) Add them all to some extension project
3) Set ``cuba.automaticDatabaseUpdate = true``
4) Start the application 
In my environment: baseaunt depends on basegranny, basegrannny depends on basebro and basema etc.
![image](https://user-images.githubusercontent.com/19840141/79051980-60b02b80-7c44-11ea-9066-b39f5f192e96.png)

- Actual behavior
DB updater will not execute the scripts from the last (alphabetically sorted) folder. It might be a component (not the extension project).

**Comment by andreysubbotin** [comment]
Dependent pull request: #133

**Comment by soraksh** [comment]
Related commits;
