### ISSUE TITLE
buildUberJar create empty manifest file when using Java 8

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba-gradle-plugin#140]
### Environment
forum: https://www.cuba-platform.com/discuss/t/uberjar-creates-app-jar-with-0-byte-manifest-mf/12349/3

reproduced by me on Ubuntu 20.04, OpenJDK 8 1.8.0_252 (openjdk-8-jdk package).

- Platform version: 7.2.3, 7.2.4
- Gradle version: 5.6.4

### Description of the bug or enhancement
- Download https://github.com/cuba-platform/sample-session-planner sample
- Switch project SDK and Gradle SDK to java 8.
- Create UberJar task with Studio:
```
task buildUberJar(type: CubaUberJarBuilding) {
    singleJar = true
    appProperties = ['cuba.automaticDatabaseUpdate': true]
}
```
- CUBA -> Deployment -> Build UberJAR

- Run created jar file:
```
$ java -jar app.jar 
Error: Unable to access jarfile app.jar
```
If you open the jar file, you will see that manifest.mf is empty.

Not reproduced with openjdk-11.

**Comment by gmlion** [comment]
I'm having the same issue with Platform 6.10.17. Could it be related?
