### ISSUE TITLE
Update tomcat to 9.0.28 in order to be able to set SameSite=None cookie policy

### ISSUE THREAD

**Issue by glebshalyganov** [cuba-platform/cuba-gradle-plugin#144]
### Environment

- Platform version: 7.2.7

### Description of the bug or enhancement

Due to the [recent security update in Chrome ](https://blog.chromium.org/2019/10/developers-get-ready-for-new.html) in some cases it is needed to set the `SameSite=None` cookie setting (for example, when using the SAML add-on).

But it is impossible with tomcat < 9.0.28 because of the bug: https://bz.apache.org/bugzilla/show_bug.cgi?id=63865.

**Comment by andreysubbotin** [comment]
Update Tomcat to 9.0.38

**Comment by andreysubbotin** [comment]
For QA: Application smoke test and WebSockets check.
