### ISSUE TITLE
Migrate to Gradle 6 to get rid of "path too long" widgetset building problem

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba-gradle-plugin#146]
### Environment
- Platform version: 7.2.

### Description of the bug or enhancement
- use Windows
- create project
- add several add-ons, e.g. like below:
```
    appComponent("com.haulmont.cuba:cuba-global:$cubaVersion")
    appComponent("com.haulmont.reports:reports-global:$cubaVersion")
    appComponent("com.haulmont.charts:charts-global:$cubaVersion")
    appComponent('de.diedavids.cuba.instantlauncher:instantlauncher-global:0.5.0')
    appComponent('com.haulmont.addon.admintools:cuba-at-global:1.5.1')
    appComponent('com.haulmont.addon.emailtemplates:yet-global:1.4.2')
    appComponent('com.haulmont.addon.restapi:restapi-global:7.2.2')
```
- Studio automatically creates app-web-toolkit module
- try to run the application

Actual:
building project fails, because of the "Error 206 path too long" problem. This is really a blocker for Windows users.

Problem is known for a long time: #14.

Workaround is tedious: https://doc.cuba-platform.com/manual-7.2/widgetset_win_path_too_long.html

According to some Haulmont developers, you can get rid of this problem by upgrading project to Gradle 6.1.

However, there may be some incompatibilities, so we must be careful.

If implemented, also to be done in CUBA Studio project template.

**Comment by andreysubbotin** [comment]
Gradle doesn't fix the problem with`BuildWidgetSet` and long classpath. So update to Gradle 6 was reverted. The original problem is fixed in #14

**Comment by alexbudarov** [comment]
Haha, why then devs from Custom Solutions told us it helped them?

**Comment by andreysubbotin** [comment]
This may work for other Java processes but not for `widgetSet`.
