### ISSUE TITLE
Plugin Error: Plugin "CUBA" is incompatible (supported only in IntelliJ IDEA).

### ISSUE THREAD

**Issue by aresrazari** [cuba-platform/cuba-gradle-plugin#148]
### Description of the bug

- I recently installed a number of various plugins to see how they could help improve my productivity when working with Android Studio. Among them was the CUBA. 
- A couple of things to add before I go on why is it still visible in the Android Studio Plugin Marketplace with conflicting messages on its functionality in Android Studio on JetBrains Marketplace vs when it's actually installed. It doesn't damage my projects in any way for which I am grateful, but it is annoying that every time I open Android Studio the error above is the first thing I see a red notification in my Event Log.
- When I check the plugin list it's not listed as installed. I have been digging around in the plugins folder in the installation folder trying to figure out which jar file I need to delete so that that message disappears but I don't even know what's triggering the message so I might end up doing more harm. Anyone out there, I'm feeling trapped on the event horizon and I need someone to help me reach escape velocity lest I face spaghettification into the black hole of documentation?

### Environment

- Platform version: Android Studio V4.1
- Gradle version: 4.1.0
- Operating system: Windows

**Comment by alexbudarov** [comment]
Hi,
Please use this forum to report problems related to the CUBA plugin:
https://www.cuba-platform.com/discuss/
