### ISSUE TITLE
Unable to use JavaCV added as a dependency

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/cuba-gradle-plugin#151]
### Environment

- Platform version: 7.2.11
- Gradle version: 5.6.4
- Forum issues: 
https://www.cuba-platform.com/discuss/t/strange-behavior-with-javacv-added-as-dependency/14489
https://www.cuba-platform.com/discuss/t/unable-to-use-javacv-in-cuba-project/14564 

### Description of the bug or enhancement

1. Add only two dependencies 
```
compile 'org.bytedeco:javacv:1.5.4'
compile 'org.bytedeco:javacpp:1.5.4'
```
both jars will be copied to shared/lib in tomcat after deployment from Studio.
![image.png](https://images.zenhubusercontent.com/5ae335564b5806bc2bd0e9cf/92d08401-1eb2-4a4e-8393-029b46cb049e)
2. Add other dependencies
```
compile 'org.bytedeco:javacv:1.5.4'
compile 'org.bytedeco:javacpp:1.5.4'
compile 'org.bytedeco:ffmpeg-platform:4.3.1-1.5.4'
compile 'org.bytedeco:opencv-platform:4.4.0-1.5.4'
```
![image.png](https://images.zenhubusercontent.com/5ae335564b5806bc2bd0e9cf/7cc5ffcc-c785-4dc3-aef7-9169670685dc)
*A.R.*
javacpp-1.5.4.jar will be deleted, which will cause runtime issue working with API in javacpp.
There is no problem in other non-CUBA projects, with Maven or Gradle is used

**Comment by BryanYin** [comment]
Hi, just got feedback from customer, javacv issue is fixed, but have new issue, `org.bytedeco:opencv:4.5.1-1.5.5` is not deployed now. Adding below to build.gradle:

```
  compile 'org.bytedeco:javacpp:1.5.5'
  compile 'org.bytedeco:ffmpeg-platform:4.3.2-1.5.5'
  compile 'org.bytedeco:opencv:4.5.1-1.5.5'
  compile 'org.bytedeco:opencv-platform:4.5.1-1.5.5'
  compile 'org.bytedeco:cuda-platform:11.2-8.1-1.5.5'
  compile 'org.bytedeco:opencv-platform-gpu:4.5.1-1.5.5'
```

missing jar is:
`opencv-4.5.1-1.5.5.jar`
