### ISSUE TITLE
setupTomcat task fails to update conf/server.xml file if non-default ajpPort set in the project

### ISSUE THREAD

**Issue by Gasloff** [cuba-platform/cuba-gradle-plugin#152]
If project has non-default ajpPort set in the build.gradle, then cuba gradle plugin tries to set it for AJP connector in tomcat/conf/server.xml.
But this connector is commented out in default server.xml file.
So the task shows the following message: 
`conf/server.xml has not been updated: cannot find AJP Connector node`
As a result server.xml file is in a default state with default ports (HTTP connector port, AJP connector port, server shutdown port)

See also https://youtrack.cuba-platform.com/issue/STUDIO-9123

**Comment by natfirst** [comment]
For QA: check smoke for IDP addon after fix

**Comment by DartVerder** [comment]
The AJP port cannot be changed, an error message appears `cannot find AJP Connector node`. 
If you uncomment this port in a file `conf/server.xml`, and change AJP port in Project Properties, the port will be commented out again.
