### ISSUE TITLE
Unable to apply plugin in Gradle 7.2 because compile() method in CubaPlugin.groovy

### ISSUE THREAD

**Issue by iamolever** [cuba-platform/cuba-gradle-plugin#159]
https://github.com/cuba-platform/cuba-gradle-plugin/blob/4a7bd034121989c3ba516a31c3ecadfb58ed4673/src/main/groovy/CubaPlugin.groovy#L903

**Comment by knstvk** [comment]
Only Gradle 5.6.4 is supported.
