### ISSUE TITLE
Warn about possible JAR hell during deployment to tomcat

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba-gradle-plugin#18]
Disable sharedLibResolve by default
Check if there are duplicated jars and write warning to build logs
Offer to resove dependency problems in build.gradle

---
Original issue: https://youtrack.haulmont.com/issue/PL-9656

**Comment by dtsaryov** [comment]
Won't fix. Suggested to add an ability to configure Gradle tasks logging level in Studio: [YouTrack](https://youtrack.cuba-platform.com/issue/STUDIO-6449)
