### ISSUE TITLE
Interactive progress for UberJar task

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba-gradle-plugin#19]
See feature/advanced-progress-logging of cuba-gradle-plugin
- https://github.com/cuba-platform/cuba-gradle-plugin/tree/feature/advanced-progress-logging
- https://issues.gradle.org/browse/GRADLE-2787

**Comment by jreznot** [comment]
Check this plugin https://github.com/radarsh/gradle-test-logger-plugin
