### ISSUE TITLE
Use standard Gradle compileOnly configuration instead of provided

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba-gradle-plugin#27]
Custom `provided` configuration will be removed and replaced with standard `compileOnly`

See https://blog.gradle.org/introducing-compile-only-dependencies

---
Original issue: https://youtrack.haulmont.com/issue/PL-10394

**Comment by dtsaryov** [comment]
A ticket for CUBA Studio: [YouTrack](https://youtrack.cuba-platform.com/issue/STUDIO-4645).
