### ISSUE TITLE
Composite builds approach for app component development

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba-gradle-plugin#28]
https://docs.gradle.org/current/userguide/composite_builds.html

**Comment by dtsaryov** [comment]
Gradle doesn't resolve 'zip' dependencies now: https://github.com/gradle/gradle/issues/4491

It prevents us to resolve `webcontent` configuration dependencies from composite builds.

**Comment by jreznot** [comment]
Removed from 7.0 release
Waiting for solution of the attached Gradle issue.

**Comment by dtsaryov** [comment]
A solution is proposed in Gradle issue. Needs to be checked
