### ISSUE TITLE
Simplify Bintray components uploading

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba-gradle-plugin#32]
See: https://www.cuba-platform.com/discuss/t/recommendations-on-developing-application-components/4715

Implement built-in support for Bintray uploads

---
Original issue: https://youtrack.haulmont.com/issue/PL-10737

**Comment by dtsaryov** [comment]
Implemented in CUBA CLI Plugin: [cuba-platform/cli-bintray-publisher](https://github.com/cuba-platform/cli-bintray-publisher). Will not be fixed here.
