### ISSUE TITLE
CubaDeployment should copy DB scripts only for required database by default

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba-gradle-plugin#52]
### Environment

- Platform version: 6.9.0

### Description of the bug or enhancement

When we run:
```
> gradlew deploy
```

It copies all the hsql / postgresql / oracle / etc scripts to tomcat. But it is not necessary for typical project.

Let's filter scripts by default in Fast deployment / UberJAR and WAR / Single WAR deployments

**Comment by dtsaryov** [comment]
Decided not to do this enhancement, because there are cases when WAR or UberJAR are built to be able to work with all databases.
