### ISSUE TITLE
Set project file encoding to UTF-8 by default

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba-gradle-plugin#55]
Previously, we have set it on .ipr file generation

### QA

You have to download Intellij IDEA 2019.1 to check the issue: [IJ IDEA EAP](https://www.jetbrains.com/idea/nextversion/).

Check in settings (`Ctrl + Alt + S` for Win) that the following fields are set to `UTF-8` after project import:

![image](https://user-images.githubusercontent.com/6183810/54900618-64fc9000-4eed-11e9-9c9c-6c3218a387de.png)

**Comment by dtsaryov** [comment]
The gradle idea ext plugin doesn't provide a way to do it right now. 

Postpone until the related issue will be resolved: JetBrains/gradle-idea-ext-plugin#29

**Comment by jreznot** [comment]
Changes in plugin https://github.com/JetBrains/gradle-idea-ext-plugin/wiki/DSL-spec-v.-0.5#encoding-settings-requires-idea-20191
