### ISSUE TITLE
Add more strong password hashing algorithm

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba-gradle-plugin#8]
http://techblog.bozho.net/the-hash-challenge/

Also, use special stored salt in SEC_USER table

---
Original issue: https://youtrack.haulmont.com/issue/PL-4803

**Comment by jreznot** [comment]
Issue moved to [cuba-platform/cuba #868](https://github.com/cuba-platform/cuba/issues/868) via [**ZenHub**](https://www.zenhub.com/)
