### ISSUE TITLE
Increase tomcat wait time after stop on Windows 

### ISSUE THREAD

**Issue by andreysubbotin** [cuba-platform/cuba-gradle-plugin#91]
### Description of the bug or enhancement

```
Unable to delete file: C:\BuildAgent\work\387912e0b0fb1630\deploy\tomcat\bin\bootstrap.jar
```

### Updates

`waitTimeout` property added for the `dropTomcat` task:

```
dropTomcat {
    waitTimeout = 30
}
```

**Comment by jreznot** [comment]
Let's move this timeout to stop task property so we could set it from project
