### ISSUE TITLE
CubaUberJarBuilding : polymerProject is not accessible any more

### ISSUE THREAD

**Issue by clumsym76** [cuba-platform/cuba-gradle-plugin#96]
In former version (before 7.0) was it possible to overwrite the frontProject in task buildUberJar by usage of **polymerProject**

=> cuba-gradle-plugin/src/main/groovy/CubaUberJarBuilding.groovy

The documentation still contains
`polymerProject - a Gradle project representing the Polymer UI module. If not defined, the standard polymer-client module is used.`
please see at https://doc.cuba-platform.com/manual-7.0/build.gradle_buildUberJar.html

Is it possible to reenable it soon?

### Environment

- Platform version: 7.0.1 
- Gradle version: 4.10.3
- Operating system: Mac OS X 10.14.3 x86_64

### Description of the bug or enhancement

- Minimal reproducible example:
`task buildUberJar(type: CubaUberJarBuilding) {
    polymerProject = frontModule
    polymerBuildDir = "../dist/ista-front"
}`

- Expected behavior:
Parameter polymerProject will be used to include frontProject while building UberJar

- Actual behavior:
Error message
`> Could not set unknown property 'polymerProject' for task ':buildUberJar' of type CubaUberJarBuilding.
`

**Comment by clumsym76** [comment]
Please tell us when a fix could be available? Thx!

**Comment by andreysubbotin** [comment]
Thank you for reporting the problem.
You can use `frontProject` instead of `polymerProject`. 
We are going to update documentation and release notes for 7.0 according to this changes.

**Comment by andreysubbotin** [comment]
Documentation:
https://github.com/cuba-platform/documentation/commit/1ff189b88bef8a01aa40cb7bb113d4f894891d50
Release notes:

**Comment by clumsym76** [comment]
Now it is possible to use frontProject but it has no effect, the build artifacts from the front project will not be part of the UberJar.

`> Task :buildUberJar
[CubaUberJAR] Copy shared libs for project ':ista-core'
[CubaUberJAR] Copy app libs for project ':ista-core'
[CubaUberJAR] Copy shared libs for project ':ista-web'
[CubaUberJAR] Copy app libs for project ':ista-web'
[CubaUberJAR] Pack server libs
[CubaUberJAR] Pack libs progress: 0%
[CubaUberJAR] Pack libs progress: 20%
[CubaUberJAR] Pack libs progress: 40%
[CubaUberJAR] Pack libs progress: 60%
[CubaUberJAR] Pack libs progress: 80%
[CubaUberJAR] Pack libs progress: 100%
[CubaUberJAR] Pack app libs for project ':ista-core'
[CubaUberJAR] Pack libs progress: 0%
[CubaUberJAR] Pack libs progress: 20%
[CubaUberJAR] Pack libs progress: 40%
[CubaUberJAR] Pack libs progress: 60%
[CubaUberJAR] Pack libs progress: 100%
[CubaUberJAR] Pack content for project ':ista-core'
[CubaUberJAR] Pack app libs for project ':ista-web'
[CubaUberJAR] Pack libs progress: 0%
[CubaUberJAR] Pack libs progress: 20%
[CubaUberJAR] Pack libs progress: 40%
[CubaUberJAR] Pack libs progress: 60%
[CubaUberJAR] Pack libs progress: 80%
[CubaUberJAR] Pack libs progress: 100%
[CubaUberJAR] Pack shared libs for project ':ista-web'
[CubaUberJAR] Pack libs progress: 0%
[CubaUberJAR] Pack libs progress: 20%
[CubaUberJAR] Pack libs progress: 40%
[CubaUberJAR] Pack libs progress: 60%
[CubaUberJAR] Pack libs progress: 80%
[CubaUberJAR] Pack libs progress: 100%
[CubaUberJAR] Pack content for project ':ista-web'
[CubaUberJAR] Pack libs progress: 0%
[CubaUberJAR] Pack libs progress: 100%
`

**Comment by clumsym76** [comment]
Thx!
